---
# name: continuous Deployment

# on: push

# jobs:
#   hello-gh-actions:
#     name: Hello Github hello-gh-actions
#     runs-on: ubuntu-20.04
#     steps:
#       - name: checkout
#         uses: actions/checkout@v2
#       - name: Run Tests
#         run: echo "Running Tests"

# Runs the tests and does linting of the project
# on: push

# jobs:
#   test:
#     name: Test
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Test
#         run: docker-compose run --rm app sh -c "python manage.py test"
#   lint:
#     name: lint
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: lint
#         run: docker-compose run --rm app ssh -c "flake8"

# configuration only runs if a push is made to main or production

on: 
  push:
    branches:
      - main
      - production 
  pull_request: []
    

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
  lint:
    name: lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: lint
        run: docker-compose run --rm app ssh -c "flake8"

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-20.04
    needs: [test, lint]
    if: github.ref == 'refs/heads/main' # only run if the change being made is being merged into main branch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to staging
      run: echo "Deploy to staging code here"

  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-20.04
    needs: [test, lint]
    if: github.ref == 'refs/heads/production' # only run if the change being made is being merged into main branch
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deploy to staging
      run: echo "Deploy to Production code here"
